// AI Mentor page: select a project, enter a requirement, choose a task type,
// and generate a mock structured AI response. No external AI call is made.

import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import {
  Sparkles,
  Save,
  ListPlus,
  Eraser,
  Brain,
  Monitor,
  Server,
  Database,
  TestTube,
  AlertOctagon,
  Target,
} from 'lucide-react'
import { useAppData } from '../context/AppDataContext'
import { aiTaskTypes } from '../data/mockData'
import LoadingSpinner from '../components/Common/LoadingSpinner'
import SuccessMessage from '../components/Common/SuccessMessage'
import ErrorMessage from '../components/Common/ErrorMessage'

// Build a realistic mock response based on the chosen task type and prompt.
function buildMockResponse(taskType, prompt, projectName) {
  return {
    understanding: `${taskType} for "${projectName}". Requirement: ${prompt}`,
    frontendTasks: [
      'Create the main page layout and responsive navigation',
      'Build the primary data entry form with client-side validation',
      'Add a results list with loading and empty states',
      'Wire the UI to the FastAPI endpoints using Axios',
    ],
    backendTasks: [
      'Define Pydantic request/response schemas',
      'Implement the FastAPI router and endpoint handlers',
      'Add input validation and clear error responses',
      'Protect write endpoints with authentication',
    ],
    databaseTasks: [
      'Create the required tables and relations in SQL Server',
      'Add indexes on frequently filtered columns',
      'Write a migration script for the initial schema',
    ],
    testingSteps: [
      'Unit test the API endpoints with TestClient',
      'Integration test the full create/read flow',
      'Manual test the form validation in the browser',
      'Verify error states and empty states',
    ],
    blockers: [
      'SQL Server connection pooling under concurrent requests',
      'Handling large file uploads if resumes are involved',
      'Keeping the Ollama API key in the backend only',
    ],
    nextAction: 'Start with the database schema, then the FastAPI endpoints, then the React UI.',
  }
}

export default function AIMentorPage() {
  const navigate = useNavigate()
  const { projects, addAIInteraction, addTask } = useAppData()

  const [form, setForm] = useState({
    projectId: projects[0]?.id || '',
    prompt: '',
    taskType: 'Break Requirement into Tasks',
  })
  const [errors, setErrors] = useState({})
  const [loading, setLoading] = useState(false)
  const [response, setResponse] = useState(null)
  const [message, setMessage] = useState('')
  const [error, setError] = useState('')

  function setField(name, value) {
    setForm((f) => ({ ...f, [name]: value }))
    if (errors[name]) setErrors((e) => ({ ...e, [name]: undefined }))
  }

  function validate() {
    const e = {}
    if (!form.projectId) e.projectId = 'Please select a project.'
    if (!form.prompt.trim()) e.prompt = 'Please enter a requirement or question.'
    setErrors(e)
    return Object.keys(e).length === 0
  }

  function handleGenerate() {
    if (!validate()) return
    setError('')
    setMessage('')
    setLoading(true)
    // Simulate the future POST /api/ai/plan call
    setTimeout(() => {
      const project = projects.find((p) => p.id === form.projectId)
      const res = buildMockResponse(form.taskType, form.prompt.trim(), project?.name || 'Project')
      setResponse(res)
      setLoading(false)
      setMessage('AI recommendation generated.')
    }, 1400)
  }

  function handleSave() {
    if (!response) return
    const project = projects.find((p) => p.id === form.projectId)
    addAIInteraction({
      projectId: form.projectId,
      taskType: form.taskType,
      userPrompt: form.prompt.trim(),
      responsePreview: response.nextAction,
      modelName: 'GPT-OSS 20B (mock)',
      response,
    })
    setMessage('Recommendation saved to AI History.')
  }

  function handleCreateTasks() {
    if (!response) return
    // Create tasks from the frontend + backend + database sections
    const sections = [
      { label: 'Frontend', tasks: response.frontendTasks },
      { label: 'Backend', tasks: response.backendTasks },
      { label: 'Database', tasks: response.databaseTasks },
    ]
    sections.forEach((sec) => {
      sec.tasks.forEach((title) => {
        addTask({
          projectId: form.projectId,
          title: `${sec.label}: ${title}`,
          description: `Generated by AI Mentor — ${form.taskType}`,
          priority: 'Medium',
          status: 'Pending',
          aiGenerated: true,
        })
      })
    })
    setMessage('Tasks created from the recommendation.')
  }

  function handleClear() {
    setResponse(null)
    setForm((f) => ({ ...f, prompt: '' }))
    setMessage('')
    setError('')
  }

  return (
    <div>
      <div className="page-header">
        <div>
          <h2>AI Mentor</h2>
          <div className="subtitle">
            Ask the AI to plan, break down or review your project requirements.
          </div>
        </div>
      </div>

      <div className="ai-form-card">
        <div className="form-row">
          <div className="form-group">
            <label htmlFor="ai-project">Select Project</label>
            <select
              id="ai-project"
              value={form.projectId}
              onChange={(e) => setField('projectId', e.target.value)}
            >
              <option value="">— Select a project —</option>
              {projects.map((p) => (
                <option key={p.id} value={p.id}>{p.name}</option>
              ))}
            </select>
            {errors.projectId && <div className="form-error">{errors.projectId}</div>}
          </div>
          <div className="form-group">
            <label htmlFor="ai-task-type">AI Task Type</label>
            <select
              id="ai-task-type"
              value={form.taskType}
              onChange={(e) => setField('taskType', e.target.value)}
            >
              {aiTaskTypes.map((t) => (
                <option key={t.value} value={t.value}>{t.label}</option>
              ))}
            </select>
          </div>
        </div>

        <div className="form-group">
          <label htmlFor="ai-prompt">Requirement or Question</label>
          <textarea
            id="ai-prompt"
            rows={4}
            value={form.prompt}
            onChange={(e) => setField('prompt', e.target.value)}
            placeholder="Describe what you want the AI to help with..."
            aria-invalid={!!errors.prompt}
          />
          {errors.prompt && <div className="form-error">{errors.prompt}</div>}
        </div>

        <div className="form-actions">
          <button className="btn-primary" onClick={handleGenerate} disabled={loading}>
            <Sparkles size={16} /> Generate AI Recommendation
          </button>
        </div>
      </div>

      {message && <SuccessMessage message={message} onDismiss={() => setMessage('')} />}
      {error && <ErrorMessage message={error} onDismiss={() => setError('')} />}

      {loading && (
        <div className="card card-pad" style={{ marginBottom: '1.25rem' }}>
          <LoadingSpinner message="AI Mentor is analysing your project…" />
        </div>
      )}

      {response && !loading && (
        <>
          <div className="ai-response" style={{ marginBottom: '1.25rem' }}>
            <Section icon={Brain} color="indigo" title="Requirement Understanding">
              <p>{response.understanding}</p>
            </Section>

            <Section icon={Monitor} color="blue" title="Frontend Tasks">
              <TaskList tasks={response.frontendTasks} color="blue" />
            </Section>

            <Section icon={Server} color="cyan" title="Backend Tasks">
              <TaskList tasks={response.backendTasks} color="cyan" />
            </Section>

            <Section icon={Database} color="indigo" title="Database Tasks">
              <TaskList tasks={response.databaseTasks} color="indigo" />
            </Section>

            <Section icon={TestTube} color="green" title="Testing Steps">
              <ul>
                {response.testingSteps.map((s, i) => <li key={i}>{s}</li>)}
              </ul>
            </Section>

            <Section icon={AlertOctagon} color="red" title="Possible Blockers">
              <ul>
                {response.blockers.map((b, i) => <li key={i}>{b}</li>)}
              </ul>
            </Section>

            <Section icon={Target} color="green" title="Recommended Next Action">
              <p style={{ fontWeight: 600 }}>{response.nextAction}</p>
            </Section>
          </div>

          <div className="card card-pad" style={{ display: 'flex', gap: '0.6rem', flexWrap: 'wrap' }}>
            <button className="btn-primary" onClick={handleSave}>
              <Save size={16} /> Save Recommendation
            </button>
            <button className="btn-secondary" onClick={handleCreateTasks}>
              <ListPlus size={16} /> Create Tasks from Recommendation
            </button>
            <button className="btn-secondary" onClick={handleClear}>
              <Eraser size={16} /> Clear Response
            </button>
            <button className="btn-ghost" onClick={() => navigate('/ai-history')}>
              View AI History
            </button>
          </div>
        </>
      )}

      {!response && !loading && (
        <div className="card card-pad" style={{ textAlign: 'center', color: 'var(--text-muted)' }}>
          Choose a project, describe your requirement and click <strong>Generate AI Recommendation</strong> to see a structured mock response.
        </div>
      )}
    </div>
  )
}

function Section({ icon: Icon, color, title, children }) {
  const colorMap = {
    blue: ['var(--blue-50)', 'var(--blue-600)'],
    indigo: ['var(--indigo-50)', 'var(--indigo-600)'],
    cyan: ['var(--cyan-50)', 'var(--cyan-600)'],
    green: ['var(--success-light)', 'var(--success)'],
    red: ['var(--error-light)', 'var(--error)'],
  }
  const [bg, fg] = colorMap[color] || colorMap.blue
  return (
    <div className="ai-section">
      <h4>
        <span className="ai-section-icon" style={{ background: bg, color: fg }}>
          <Icon size={16} />
        </span>
        {title}
      </h4>
      {children}
    </div>
  )
}

function TaskList({ tasks, color }) {
  const bgMap = {
    blue: 'var(--blue-500)',
    cyan: 'var(--cyan-500)',
    indigo: 'var(--indigo-500)',
  }
  return (
    <ul className="ai-task-list">
      {tasks.map((t, i) => (
        <li className="ai-task-item" key={i}>
          <span className="ai-task-bullet" style={{ background: bgMap[color] || 'var(--blue-500)' }}>
            {i + 1}
          </span>
          <span>{t}</span>
        </li>
      ))}
    </ul>
  )
}
